export const levelsInstructions = [
  {
    level: 1,
    difficulty: 'beginner',
    tokens: [
      {
        type: 'laser',
        x: 1,
        y: 1,
        isFixed: true,
        rotatePos: 'right',
        // isSetOnBoard: false,
      },
      {
        type: 'target',
        x: 3,
        y: 3,
        isFixed: true,
        rotatePos: 'top',
      },
      {
        type: 'mirror',
        x: 1,
        y: 3,
        isFixed: false,
        isRotate: true,
        finalRotatePos: 'bottom',
        rotatePos: 'bottom',
      },
    ],
  },
  {
    level: 2,
    difficulty: 'intermediate',
    tokens: [
      {
        type: 'laser',
        x: 0,
        y: 4,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'target',
        x: 4,
        y: 0,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 0,
        y: 3,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 4,
        y: 3,
        isFixed: false,
        rotatePos: 'right',
      },
    ],
  },
  {
    level: 3,
    difficulty: 'advanced',
    tokens: [
      {
        type: 'laser',
        x: 0,
        y: 4,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'target',
        x: 4,
        y: 0,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 0,
        y: 3,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 4,
        y: 3,
        isFixed: false,
        rotatePos: 'right',
      },
    ],
  },
  {
    level: 4,
    difficulty: 'expert',
    tokens: [
      {
        type: 'laser',
        x: 0,
        y: 4,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'target',
        x: 4,
        y: 0,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 0,
        y: 3,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 4,
        y: 3,
        isFixed: false,
        rotatePos: 'right',
      },
    ],
  },
  {
    level: 5,
    difficulty: 'advanced',
    tokens: [
      {
        type: 'laser',
        x: 0,
        y: 4,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'target',
        x: 4,
        y: 0,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 0,
        y: 3,
        isFixed: true,
        rotatePos: 'right',
      },
      {
        type: 'mirror',
        x: 4,
        y: 3,
        isFixed: false,
        rotatePos: 'right',
      },
    ],
  },
];
